// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TripPlanner.Adapters.Persistence.Ef.Persistence.Db;

#nullable disable

namespace TripPlanner.Adapters.Persistence.Ef.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250916231155_AddDateOptionsAndVotes")]
    partial class AddDateOptionsAndVotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TripPlanner.Adapters.Persistence.Ef.Persistence.Models.DateOptionRecord", b =>
                {
                    b.Property<Guid>("DateOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateIso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TripId")
                        .HasColumnType("TEXT");

                    b.HasKey("DateOptionId");

                    b.HasIndex("TripId", "DateIso")
                        .IsUnique();

                    b.ToTable("DateOptions", (string)null);
                });

            modelBuilder.Entity("TripPlanner.Adapters.Persistence.Ef.Persistence.Models.DateVoteRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DateOptionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DateOptionId", "UserId")
                        .IsUnique();

                    b.ToTable("DateVotes", (string)null);
                });

            modelBuilder.Entity("TripPlanner.Adapters.Persistence.Ef.Persistence.Models.TripParticipantRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TripId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TripId", "UserId")
                        .IsUnique();

                    b.ToTable("TripParticipants", (string)null);
                });

            modelBuilder.Entity("TripPlanner.Adapters.Persistence.Ef.Persistence.Models.TripRecord", b =>
                {
                    b.Property<Guid>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("TEXT");

                    b.HasKey("TripId");

                    b.ToTable("Trips", (string)null);
                });

            modelBuilder.Entity("TripPlanner.Adapters.Persistence.Ef.Persistence.Models.DateOptionRecord", b =>
                {
                    b.HasOne("TripPlanner.Adapters.Persistence.Ef.Persistence.Models.TripRecord", null)
                        .WithMany("DateOptions")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TripPlanner.Adapters.Persistence.Ef.Persistence.Models.DateVoteRecord", b =>
                {
                    b.HasOne("TripPlanner.Adapters.Persistence.Ef.Persistence.Models.DateOptionRecord", null)
                        .WithMany("Votes")
                        .HasForeignKey("DateOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TripPlanner.Adapters.Persistence.Ef.Persistence.Models.TripParticipantRecord", b =>
                {
                    b.HasOne("TripPlanner.Adapters.Persistence.Ef.Persistence.Models.TripRecord", null)
                        .WithMany("Participants")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TripPlanner.Adapters.Persistence.Ef.Persistence.Models.DateOptionRecord", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("TripPlanner.Adapters.Persistence.Ef.Persistence.Models.TripRecord", b =>
                {
                    b.Navigation("DateOptions");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
